name = "Zarr"
uuid = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de>"]
version = "0.2.0"

[deps]
AWSCore = "4f1ea46c-232b-54a6-9b17-cc2d0f3e6598"
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
AWSSDK = "0d499d91-6ae5-5d63-9313-12987b87d5ad"
Blosc = "a74b3585-a348-5f62-a45c-50e91977d574"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.1"

[extras]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Conda", "PyCall"]
